### ISSUE TITLE
OpenAPI specification

### ISSUE THREAD

**Issue by erunion** [dword4/nhlapi#13]
Fantastic findings!

I've been slowly working on pulling together OpenAPI specifications for some of the major leagues as a side project of mine, and spent the past weekend using your endpoint documentation as the basis for one an NHL spec. 

I don't know if you'd be interested in linking to it in your docs for anyone who wants to utilize it, but it's available here: https://github.com/erunion/sport-api-specifications/tree/master/nhl

👍

**Comment by dword4** [comment]
Oh that looks much better than the raw API itself, I will definitely link to it as this probably slots into even more projects and helps speed up the development process.

**Comment by dword4** [comment]
Added!

**Comment by erunion** [comment]
Awesome, thanks again for the hard work pulling all this together.
