### ISSUE TITLE
Typo in schedule endDate parameter

### ISSUE THREAD

**Issue by sbstp** [dword4/nhlapi#8]
`GET https://statsapi.web.nhl.com/api/v1/schedule?teamId=30?startDate=2018-01-02&endDate=20128-01-02`

The end date is slightly too far into the future.

**Comment by dword4** [comment]
Fixed in commit [b8269d5](https://github.com/dword4/nhlapi/commit/b8269d51c83e2137f7997c68271fb4f25beef16b)
